server:
  port: 8080

spring:
  datasource:
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: jdbc:mysql://188.68.236.142:3306/smc_db_dev?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: dev

scaffolding-app:
  jwtCookieName:  "scma-coockie"
  jwtSecret: "secret-key-to-generate-later"
  jwtExpirationMs: 86400000





