server:
  port: 8080

spring:
  datasource:
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    url: jdbc:mysql://188.68.236.142:3306/smc_db_dev?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
    show-sql: true
  profiles:
    active: dev

  mail:
    host: 192.168.1.150
    port: 1025
    username:
    password:
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
      cache: false

scaffolding-app:
  jwtCookieName:  "scma-coockie"
  jwtSecret: "secret-key-to-generate-later"
  jwtExpirationMs: 86400000
  cors:
    allowed-origins: '*'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        secret: null
        base64-secret: ODI5NWM1NWRiNGRiY2U2MzJlY2Y2MGZkM2QxYWZhNTliM2RiMDRiZGJjYjhlZTg2ZTk0MjMzMTUzMTY5MWJkZjk0MDQ3NDNmNTlkNjM0NDE0NGRiNGNjOGQ0Mzg3ODE4ZTk4OTkzNmE1MmIzODdkNWFjNmI5NjQ4ZDU4NTllOWU=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000




