CREATE DATABASE smc_db_dev;
CREATE TABLE users(
	id INT AUTO_INCREMENT,
	username VARCHAR(30) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(200) NOT NULL, PRIMARY KEY (id)
	);
CREATE TABLE roles(
	id INT AUTO_INCREMENT,
	name VARCHAR(20),PRIMARY KEY (id)
);
CREATE TABLE user_roles(
	id INT AUTO_INCREMENT,
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (role_id) REFERENCES roles(id)
);		